%Load Dataset needed and agument/preprocess for use with MobileNetV2 input layer
%===============================
test_imds = imageDatastore("chest_xray/test", ...
    'IncludeSubfolders',true,'LabelSource','foldernames');
arg_test = augmentedImageDatastore([224 224],test_imds,'ColorPreprocessing','gray2rgb');

train_imds = imageDatastore("chest_xray/train", ...
    'IncludeSubfolders',true,'LabelSource','foldernames');
arg_train = augmentedImageDatastore([224 224],train_imds,'ColorPreprocessing','gray2rgb');

val_imds = imageDatastore("chest_xray/val", ...
    'IncludeSubfolders',true,'LabelSource','foldernames');
arg_val = augmentedImageDatastore([224 224],val_imds,'ColorPreprocessing','gray2rgb');
%===============================


load('mobileNetV2_imgnet.mat')
net = lgraph_1;

options = trainingOptions('sgdm', ...
    'MaxEpochs', 2, ...
    'Shuffle', 'every-epoch', ...
    'MiniBatchSize',128,...
    'ExecutionEnvironment','parallel',... 
    'ValidationData', arg_val, ...
    'ValidationFrequency',10,...
    'ValidationPatience',3,...
    'L2Regularization',0.0001,...
    'Plots', 'training-progress');

[tNet,info] = trainNetwork(arg_train,net,options);
save('scratch_network10.mat','tNet','info','options');
